name: Sample Secure Deployment Workflow

on:
  push: 
    branches: 
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: SAST Scan
        run: grep -r -e "password" -e "keys" -e "secrets" . #grep -Ri -w '(password|passwd|pass|secret|keys)' .

  deploy: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.KWASI_TOKEN }}
          publish_dir: .

  dast:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: OWASP ZAP DAST Scan
        continue-on-error: true
        run: |
          docker run --rm \
           -v $[pwd]:/zap/wrk/:rw \
           zaproxy/zap-stable zap-baseline.py \
           -t 'https://kattafuah.github.io/csn-dast/' || true
          
